name: Build Argentum Compressor (x86 Release)

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # needed to upload assets to the Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution for x86 Release
        run: msbuild Argentum_Compressor.sln /p:"Configuration=Release;Platform=x86" /m

      - name: Package dist zip
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          $exe = "argentum_compressor/Release/argentum_compressor.exe"
          if (!(Test-Path $exe)) {
            Get-ChildItem -Recurse -Filter argentum_compressor.exe | Select-Object FullName
            throw "Expected exe not found at $exe"
          }
          Copy-Item $exe dist/
          Compress-Archive -Path dist/* -DestinationPath dist/Argentum_Compressor-x86-Release.zip -Force
          Write-Host "Created dist/Argentum_Compressor-x86-Release.zip"

      - name: Attach assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Argentum_Compressor-x86-Release.zip
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
