name: Build Argentum Compressor (x86 Release)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # needed to upload assets to the Release

    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v2

      - name: Build (x86 Release)
        run: msbuild Argentum_Compressor.sln /m /p:"Configuration=Release;Platform=x86;OutDir=build\"

      # Only package/upload when it's a Release
      - name: Package dist zip
        if: ${{ github.event_name == 'release' }}
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Copy-Item build\*.exe dist\
          Copy-Item build\*.dll dist\ -ErrorAction SilentlyContinue
          Compress-Archive -Path dist\* -DestinationPath dist\Argentum_Compressor-x86-Release.zip -Force
          Write-Host "Created dist/Argentum_Compressor-x86-Release.zip"

      - name: Attach assets to GitHub Release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Argentum_Compressor-x86-Release.zip
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
